services:
  - type: web
    name: flask-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: firebase_config.json
